name: Git-Demo-CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting
        run: echo "No linting issues found"

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run health check
        run: |
          echo 'Git Demo project is active'
          ls -R
      - name: Env Check
        run: echo "Running in ${{ github.ref_name }}"